Unit 3: Array Programming

In [2]:
import numpy as np

# New Way of Thinking

(ACTION note: get notes from phone screenshots)

# Universal Functions

(ACTION note: get notes from phone screenshots)

# Routines in Action; Reduction

In [19]:
students_gpas = np.array([[4, 3.3, 3.5, 4], [3.2, 3.8, 4, 4], [3.9, 3.9, 4, 4]], dtype=float)
students_gpas

array([[4. , 3.3, 3.5, 4. ],
       [3.2, 3.8, 4. , 4. ],
       [3.9, 3.9, 4. , 4. ]])

We do *not* want a mean across all GPAs

In [14]:
# unwanted output
round(students_gpas.mean(), 2)

3.8

## Reduction Operation

In [15]:
students_gpas.mean(axis=1)

array([3.7 , 3.75, 3.95])

In [20]:
students_gpas.mean(axis=0)

array([3.7       , 3.66666667, 3.83333333, 4.        ])

`mean()` is known as a **reduction operation**

All *ufuncs* have the built-in reduction ability.

In [42]:
study_minutes = np.zeros(100, np.uint16)
study_minutes[0] = 150
study_minutes[1] = 60
study_minutes[2:6] = [80, 60, 30, 90]
study_minutes[9::9] = 100
study_minutes.shape = 10, 10

In [51]:
np.add.reduce(study_minutes[0])

650

In [52]:
np.add.accumulate(study_minutes[0])

array([150, 210, 290, 350, 380, 470, 470, 470, 470, 650], dtype=uint64)

Reduction operations will nearly always require an axis parameter to be defined.

In [53]:
np.sum(study_minutes, axis=1)

array([650, 180, 180, 180, 180, 180, 180, 180, 180, 360], dtype=uint64)

# Plotting